version: "2.1"
services:
  #######################################
  # Core API
  #######################################
  api:
    image: "muzamil47/keeper-core-api:latest"
    env_file: "etc/default/${ENV:-dev}.env"
    command: "${CMD:-start}"
    environment:
      - APP_DATABASE_URI=${APP_DATABASE_URI:-mongodb://mongo/keeper}
    volumes:
      - ${PWD}:${APP_SRC_DIR:-/usr/src/app_src}
    ports:
      - "${PORT:-9000}:9000"
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy

